name: Development Build & Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, test, dev ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      continue-on-error: true
      
    - name: Type check
      run: npx tsc --noEmit
      continue-on-error: true
      
    - name: Build project
      run: |
        echo "Building for DEVELOPMENT environment..."
        npm run build
        
    - name: Test build output
      run: |
        echo "Checking build output..."
        ls -la out/
        echo "Build completed successfully for dev branch!"
        
    - name: Build Summary
      run: |
        echo "## Development Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Status:** ✅ Success" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment:** Development" >> $GITHUB_STEP_SUMMARY
